Resources:
  JobsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: job_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: job_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: '${self:custom.jobsTable}-${self:provider.stage}'

