service: resources
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  cloud: ${env:TARGET_CLOUD}
  region: ${env:TARGET_REGION}
  preprocessDataBucket: ${env:TASK_EXEC_PREPROCESS_DATA_BUCKET}
  cacheDataBucket: ${env:TASK_EXEC_CACHE_DATA_BUCKET}
  logDataBucket: ${env:TASK_EXEC_LOG_DATA_BUCKET}
  resultDataBucket: ${env:TASK_EXEC_RESULT_DATA_BUCKET}
  createTaskQueue: ${env:TASK_EXEC_CREATE_TASK_QUEUE}
  processTaskQueue: ${env:TASK_EXEC_PROCESS_TASK_QUEUE}
  updateTaskQueue: ${env:TASK_EXEC_UPDATE_TASK_QUEUE}
  uploadTaskIssuesQueue: ${env:TASK_EXEC_UPLOAD_TASK_ISSUES_QUEUE}
  generateTaskSummaryQueue: ${env:TASK_EXEC_GENERATE_TASK_SUMMARY_QUEUE}
  taskTable: ${env:TASK_EXEC_TASK_TABLE}
  issueTable: ${env:TASK_EXEC_ISSUE_TABLE}
  dotenv:
    path: ../.env

provider:
  name: aws
  region: ${env:TARGET_REGION}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}

resources:
  - ${file(./task-exec-preprocess-data-bucket.yml)}
  - ${file(./task-exec-cache-data-bucket.yml)}
  - ${file(./task-exec-log-data-bucket.yml)}
  - ${file(./task-exec-result-data-bucket.yml)}
  - ${file(./task-exec-queues.yml)}
  - ${file(./task-exec-task-table.yml)}
  - ${file(./task-exec-issue-table.yml)}

