service: jobs-list-resources
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  region: ${env:AWS_DEFAULT_REGION, 'us-west-2'}
  appsBucket: ${env:JOBS_LIST_APPS_BUCKET}
  sourceDataBucket: ${env:JOBS_LIST_SOURCE_DATA_BUCKET}
  logDataBucket: ${env:JOBS_LIST_LOG_DATA_BUCKET}
  submitJobQueue: ${env:JOBS_LIST_SUBMIT_JOB_QUEUE}
  processJobQueue: ${env:JOBS_LIST_PROCESS_JOB_QUEUE}
  updateJobQueue: ${env:JOBS_LIST_UPDATE_JOB_QUEUE}
  updateJobsLogStreamQueue: ${env:JOBS_LIST_UPDATE_JOBS_LOG_STREAM_QUEUE}
  jobsTable: ${env:JOBS_LIST_JOBS_TABLE}
  dotenv:
    path: ../.env

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'us-west-2'}

resources:
  - ${file(./jobs-list-apps-bucket.yml)}
  - ${file(./jobs-list-source-data-bucket.yml)}
  - ${file(./jobs-list-log-data-bucket.yml)}
  - ${file(./jobs-list-queues.yml)}
  - ${file(./jobs-list-jobs-table.yml)}

