service: task-list-resources
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  region: ${env:TARGET_REGION}
  appsBucket: ${env:TASK_LIST_APPS_BUCKET}
  sourceDataBucket: ${env:TASK_LIST_SOURCE_DATA_BUCKET}
  logDataBucket: ${env:TASK_LIST_LOG_DATA_BUCKET}
  submitTaskQueue: ${env:TASK_LIST_SUBMIT_TASK_QUEUE}
  processTaskQueue: ${env:TASK_LIST_PROCESS_TASK_QUEUE}
  updateTaskQueue: ${env:TASK_LIST_UPDATE_TASK_QUEUE}
  updateTaskLogStreamQueue: ${env:TASK_LIST_UPDATE_TASK_LOG_STREAM_QUEUE}
  taskTable: ${env:TASK_LIST_TASK_TABLE}
  dotenv:
    path: ../.env

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:TARGET_REGION}

resources:
  - ${file(./task-list-apps-bucket.yml)}
  - ${file(./task-list-source-data-bucket.yml)}
  - ${file(./task-list-log-data-bucket.yml)}
  - ${file(./task-list-queues.yml)}
  - ${file(./task-list-task-table.yml)}

