Resources:
  IssueTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: task_id
          AttributeType: S
        -
          AttributeName: task_issue_number
          AttributeType: N
      KeySchema:
        -
          AttributeName: task_id
          KeyType: HASH
        -
          AttributeName: task_issue_number
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: '${self:custom.issueTable}-${self:provider.stage}'

