Resources:
  CreateTaskQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${self:custom.createTaskQueue}"
  ProcessTaskTriggerQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${self:custom.processTaskTriggerQueue}"
  ProcessTaskQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${self:custom.processTaskQueue}"
      VisibilityTimeout: 10800
  UpdateTaskQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${self:custom.updateTaskQueue}"
  UploadTaskIssuesQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${self:custom.uploadTaskIssuesQueue}"
      VisibilityTimeout: 3000
  GenerateTaskSummaryQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${self:custom.generateTaskSummaryQueue}"
      VisibilityTimeout: 3000

