Resources:
  LogDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.logDataBucket}
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
      AccessControl: PublicRead
  LogDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: LogDataBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:${self:custom.cloud}:s3:::${self:custom.logDataBucket}/*

