Resources:
  TaskTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: task_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
        -
          AttributeName: task_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: '${self:custom.taskTable}-${self:provider.stage}'

