Resources:
  PreprocessDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.preprocessDataBucket}
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
      AccessControl: PublicRead
  PreprocessDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: PreprocessDataBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:${self:custom.cloud}:s3:::${self:custom.preprocessDataBucket}/*

