service: task-list-user-service
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  cloud: ${env:TARGET_CLOUD}
  region: ${env:TARGET_REGION}
  stage: ${self:provider.stage}
  dotenv:
    path: ../.env

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:TARGET_REGION}

resources:
  - ${file(./user-pool.yml)}
  - ${file(./identity-pool.yml)}

