service: generate-task-summary
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  cloud: ${env:TARGET_CLOUD}
  region: ${env:TARGET_REGION}
  logDataBucket: ${env:TASK_EXEC_LOG_DATA_BUCKET}
  resultDataBucket: ${env:TASK_EXEC_RESULT_DATA_BUCKET}
  generateTaskSummaryQueue: ${env:TASK_EXEC_GENERATE_TASK_SUMMARY_QUEUE}
  dotenv:
    path: ../.env

provider:
  name: aws
  region: ${env:TARGET_REGION}
  runtime: java8
  stage: ${opt:stage, 'dev'}
  endpointType: regional
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:${self:custom.cloud}:s3:::${self:custom.logDataBucket}/*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:CopyObject
        - s3:PutObject
      Resource: "arn:${self:custom.cloud}:s3:::${self:custom.resultDataBucket}/*"
    - Effect: Allow
      Action:
        - sqs:ListQueues
      Resource: "arn:${self:custom.cloud}:sqs:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:${self:custom.cloud}:sqs:*:*:${self:custom.generateTaskSummaryQueue}"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:${self:custom.cloud}:dynamodb:${self:custom.region}:${self:custom.accountid}:*"

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'

functions:
  generate-task-summary:
    handler: com.rwang5688.GenerateTaskSummaryHandler
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-execution-pipeline
    environment:
      ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      REGION: ${env:TARGET_REGION}
      LOG_DATA_BUCKET: ${env:TASK_EXEC_LOG_DATA_BUCKET}
      RESULT_DATA_BUCKET: ${env:TASK_EXEC_RESULT_DATA_BUCKET}
      GENERATE_TASK_SUMMARY_QUEUE: ${env:TASK_EXEC_GENERATE_TASK_SUMMARY_QUEUE}
      TASK_TABLE: '${env:TASK_EXEC_TASK_TABLE}-${self:provider.stage}'
      ISSUE_TABLE: '${env:TASK_EXEC_ISSUE_TABLE}-${self:provider.stage}'
    events:
      - sqs:
          arn: "arn:${self:custom.cloud}:sqs:${self:provider.region}:${self:custom.accountid}:${self:custom.generateTaskSummaryQueue}"

