service: createTask
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  cloud: ${env:TARGET_CLOUD}
  region: ${env:TARGET_REGION}
  preprocessDataBucket: ${env:TASK_EXEC_PREPROCESS_DATA_BUCKET}
  createTaskQueue: ${env:TASK_EXEC_CREATE_TASK_QUEUE}
  processTaskQueue: ${env:TASK_EXEC_PROCESS_TASK_QUEUE}
  taskTable: ${env:TASK_EXEC_TASK_TABLE}
  dotenv:
    path: ../.env
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  region: ${env:TARGET_REGION}
  runtime: python3.8
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:${self:custom.cloud}:s3:::${self:custom.preprocessDataBucket}/*"
    - Effect: Allow
      Action:
        - sqs:ListQueues
      Resource: "arn:${self:custom.cloud}:sqs:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:${self:custom.cloud}:sqs:*:*:${self:custom.createTaskQueue}"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:${self:custom.cloud}:sqs:*:*:${self:custom.processTaskQueue}"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:${self:custom.cloud}:dynamodb:${self:custom.region}:${self:custom.accountid}:*"

functions:
  createTask:
    handler: createTask.createTask
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-execution-pipeline
    environment:
      ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      REGION: ${env:TARGET_REGION}
      PREPROCESS_DATA_BUCKET: ${env:TASK_EXEC_PREPROCESS_DATA_BUCKET}
      CREATE_TASK_QUEUE: ${env:TASK_EXEC_CREATE_TASK_QUEUE}
      PROCESS_TASK_QUEUE: ${env:TASK_EXEC_PROCESS_TASK_QUEUE}
      TASK_TABLE: ${env:TASK_EXEC_TASK_TABLE}
      STAGE: ${self:provider.stage}
    events:
      - sqs:
          arn: "arn:${self:custom.cloud}:sqs:${self:provider.region}:${self:custom.accountid}:${self:custom.createTaskQueue}"

